# Generated by Django 4.0.2 on 2022-08-27 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import progoffice.models
import progoffice.myFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room1_img', models.ImageField(upload_to='student_attendance/2022/8/27/room1')),
                ('room2_img', models.ImageField(upload_to='student_attendance/2022/8/27/room2')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=4, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('face_img', models.ImageField(default='', upload_to='students', validators=[progoffice.models.Student.check_faces])),
                ('face_encodings', models.BinaryField(null=True)),
                ('courses_enrolled', models.ManyToManyField(to='progoffice.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', progoffice.myFields.DayOfTheWeekField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.classroom')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.classtiming')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_designation', models.CharField(choices=[('P', 'professor'), ('AP', 'asst. professor')], max_length=2)),
                ('teacher_status', models.CharField(choices=[('V', 'visiting'), ('P', 'permanent')], max_length=1)),
                ('face_img', models.ImageField(default='', upload_to='teachers/faces', validators=[progoffice.models.Teacher.check_faces])),
                ('face_encodings', models.BinaryField(null=True)),
                ('right_thumb_img', models.ImageField(default='', upload_to='teachers/fingerprints')),
                ('right_thumb_keypoints', models.BinaryField(null=True)),
                ('right_thumb_descriptors', models.BinaryField(null=True)),
                ('right_index_img', models.ImageField(default='', upload_to='teachers/fingerprints')),
                ('right_index_keypoints', models.BinaryField(null=True)),
                ('right_index_descriptors', models.BinaryField(null=True)),
                ('right_middle_img', models.ImageField(default='', upload_to='teachers/fingerprints')),
                ('right_middle_keypoints', models.BinaryField(null=True)),
                ('right_middle_descriptors', models.BinaryField(null=True)),
                ('right_ring_img', models.ImageField(default='', upload_to='teachers/fingerprints')),
                ('right_ring_keypoints', models.BinaryField(null=True)),
                ('right_ring_descriptors', models.BinaryField(null=True)),
                ('right_little_img', models.ImageField(default='', upload_to='teachers/fingerprints')),
                ('right_little_keypoints', models.BinaryField(null=True)),
                ('right_little_descriptors', models.BinaryField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('class_timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progoffice.classtiming')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.student')),
            ],
        ),
        migrations.CreateModel(
            name='SearchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.course')),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progoffice.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_img', models.ImageField(null=True, upload_to='teacher_attendance')),
                ('checkout_img', models.ImageField(null=True, upload_to='teacher_attendance')),
                ('checkin_time', models.DateTimeField(null=True)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
            },
        ),
    ]
