# Generated by Django 4.0.2 on 2022-08-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(null=True, to='progoffice.Course'),
        ),
    ]
