# Generated by Django 4.0.2 on 2022-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0002_teacher_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img1',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
    ]
