# Generated by Django 4.0.2 on 2022-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0002_alter_student_courses_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, null=True, to='progoffice.Course'),
        ),
    ]
