# Generated by Django 4.0.2 on 2022-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0003_teacher_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img2',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img3',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
    ]
