# Generated by Django 4.0.2 on 2022-08-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.teacher'),
        ),
    ]
