# Generated by Django 4.0.2 on 2022-05-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0005_room_rename_student_id_enrollment_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Attendance',
            new_name='StudentAttendance',
        ),
        migrations.RenameModel(
            old_name='Teacher_attendance',
            new_name='TeacherAttendance',
        ),
    ]
