# Generated by Django 4.0.2 on 2022-08-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0005_alter_attendance_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkin_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_attendance'),
        ),
    ]
