# Generated by Django 4.0.2 on 2022-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0006_alter_attendance_checkin_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/28/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/28/room2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, to='progoffice.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_designation',
            field=models.CharField(choices=[('P', 'professor'), ('AsP', 'associate professor'), ('AP', 'asst. professor'), ('Ins', 'instructor')], max_length=4),
        ),
    ]
