# Generated by Django 4.0.2 on 2022-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0006_rename_student_attendance_studentattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='img1',
            field=models.ImageField(default='', upload_to='students'),
        ),
        migrations.AddField(
            model_name='student',
            name='img2',
            field=models.ImageField(default='', upload_to='students'),
        ),
        migrations.AddField(
            model_name='student',
            name='img3',
            field=models.ImageField(default='', upload_to='students'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img1',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img2',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img3',
            field=models.ImageField(default='', upload_to='teachers'),
        ),
    ]
