# Generated by Django 4.0.2 on 2022-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0007_teacher_course_student_img1_student_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='checkin_image',
            field=models.ImageField(default='', upload_to='teacher_attendance'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='checkout_image',
            field=models.ImageField(default='', upload_to='teacher_attendance'),
        ),
    ]
