# Generated by Django 4.0.2 on 2022-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0007_alter_bulkattendance_room1_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/9/14/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/9/14/room2'),
        ),
    ]
