# Generated by Django 4.0.2 on 2022-07-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0008_teacherattendance_checkin_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='checkin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='checkout_image',
            field=models.ImageField(default='', null=True, upload_to='teacher_attendance'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='checkout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.teacher'),
        ),
    ]
