# Generated by Django 4.0.2 on 2022-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0009_alter_teacherattendance_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
    ]
