# Generated by Django 4.0.2 on 2022-07-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0010_teacher_face_encodings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='checkin_image',
            new_name='checkin_img',
        ),
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='checkout_image',
            new_name='checkout_img',
        ),
    ]
