# Generated by Django 4.0.2 on 2022-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0011_rename_checkin_image_teacherattendance_checkin_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
