# Generated by Django 4.0.2 on 2022-07-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0012_alter_room_room_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
