# Generated by Django 4.0.2 on 2022-07-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0014_teacherattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(null=True)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('checkin_img', models.ImageField(default='', upload_to='teacher_attendance')),
                ('checkout_img', models.ImageField(default='', null=True, upload_to='teacher_attendance')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
