# Generated by Django 4.0.2 on 2022-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0015_attendance_delete_teacherattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingregistration',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='img3',
        ),
        migrations.AddField(
            model_name='teacher',
            name='face_img',
            field=models.ImageField(default='', upload_to='teachers/faces'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_index_descriptors',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_index_img',
            field=models.ImageField(default='', upload_to='teachers/fingerprints'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_index_keypoints',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_little_descriptors',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_little_img',
            field=models.ImageField(default='', upload_to='teachers/fingerprints'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_little_keypoints',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_middle_descriptors',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_middle_img',
            field=models.ImageField(default='', upload_to='teachers/fingerprints'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_middle_keypoints',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_ring_descriptors',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_ring_img',
            field=models.ImageField(default='', upload_to='teachers/fingerprints'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_ring_keypoints',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_thumb_descriptors',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_thumb_img',
            field=models.ImageField(default='', upload_to='teachers/fingerprints'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='right_thumb_keypoints',
            field=models.BinaryField(null=True),
        ),
    ]
