# Generated by Django 4.0.2 on 2022-07-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0018_delete_course_remove_enrollment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_name', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progoffice.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(null=True, to='progoffice.Course'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.course'),
        ),
    ]
