# Generated by Django 4.0.2 on 2022-07-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0020_timetable_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
