# Generated by Django 4.0.2 on 2022-07-24 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import progoffice.myFields


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0021_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', progoffice.myFields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], default='', max_length=1)),
                ('time', models.TimeField(default=datetime.time(16, 0))),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='progoffice.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.room')),
            ],
        ),
    ]
