# Generated by Django 4.0.2 on 2022-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0022_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
    ]
