# Generated by Django 4.0.2 on 2022-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0023_student_face_encodings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room1_img', models.ImageField(upload_to='student_attendance/2022/7/24/room1')),
                ('room2_img', models.ImageField(upload_to='student_attendance/2022/7/24/room2')),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(),
        ),
    ]
