# Generated by Django 4.0.2 on 2022-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0024_bulkattendance_alter_timetable_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='ClassRoom',
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_enrolled',
            field=models.ManyToManyField(to='progoffice.Course'),
        ),
    ]
