# Generated by Django 4.0.2 on 2022-07-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0026_classtiming_remove_timetable_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.classtiming'),
        ),
    ]
