# Generated by Django 4.0.2 on 2022-07-30 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progoffice', '0029_rename_teacher_visitingteacher_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitingTeacher',
            new_name='Teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content_type',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progoffice.teacher'),
        ),
        migrations.DeleteModel(
            name='PermanentTeacher',
        ),
    ]
