# Generated by Django 4.0.2 on 2022-07-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0030_rename_visitingteacher_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/7/31/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/7/31/room2'),
        ),
        migrations.CreateModel(
            name='SearchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progoffice.course')),
            ],
        ),
    ]
