# Generated by Django 4.0.2 on 2022-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0031_alter_bulkattendance_room1_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/1/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/1/room2'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
