# Generated by Django 4.0.2 on 2022-08-09 14:21

from django.db import migrations, models
import django.db.models.deletion
import progoffice.myFields


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0034_alter_bulkattendance_room1_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/9/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/9/room2'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=progoffice.myFields.DayOfTheWeekField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progoffice.classtiming'),
        ),
    ]
