# Generated by Django 4.0.2 on 2022-08-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progoffice', '0035_alter_bulkattendance_room1_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='class_timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progoffice.classtiming'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room1_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/10/room1'),
        ),
        migrations.AlterField(
            model_name='bulkattendance',
            name='room2_img',
            field=models.ImageField(upload_to='student_attendance/2022/8/10/room2'),
        ),
    ]
